// apps/svelte-kit/src/components/Nav.svelte
<script>
   import { goto } from '$app/navigation';

   import Button from '$ui/Buttons/Button.svelte';
   import ButtonOutline from '$ui/Buttons/ButtonOutline.svelte';
</script>

<nav class="flex items-center space-x-6">
   <div class="flex items-center">
      <a href="#">Курсы</a>
   </div>
   <div class="flex items-center space-x-3">
      <Button on:click={() => goto('/login')}>Вход</Button>
      <ButtonOutline on:click={() => goto('/signup')}>Регистрация</ButtonOutline>
   </div>
</nav>

// apps/frontend-react/src/components/Layout/Nav.tsx
import React from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Button } from 'ui'

const Nav = () => {
   const navigate = useNavigate()

   return (
      <div className="flex items-center space-x-3">
         <Link to="/courses" className="font-proxima-medium">
            Курсы
         </Link>
         <Link to="/playground">playground</Link>
         <div className="space-x-3">
            <Button onClick={() => navigate('/login')}>Вход</Button>
            <Button onClick={() => navigate('/signup')} variant="outline">
               Регистрация
            </Button>
         </div>
      </div>
   )
}

export default Nav
